# Generated by Django 4.0.6 on 2022-07-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigpotapp', '0003_rename_author_freepost_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freepost',
            old_name='author_id',
            new_name='author',
        ),
    ]
