# Generated by Django 4.0.6 on 2022-07-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigpotapp', '0004_rename_author_id_freepost_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
